### PR TITLE
Master fix vulnerability

### PR DESCRIPTION
**Pull request by quilicicf**
Hi, 

I tried to fix all non-low vulnerabilities in the repo. 
There are two tests that don't pass:

```
 1) The copy method
       should copy with transforming when `--transform` option was specified.
         should throw an error on lib sync version (cannot use streaming api).:
     AssertionError [ERR_ASSERTION]: Missing expected exception (Error).
      at Context.it (test/copy.js:560:20)

  2) The copy method
       should copy with transforming when `--transform` option was specified (it does not have 'destroy' method).
         should throw an error on lib sync version (cannot use streaming api).:
     AssertionError [ERR_ASSERTION]: Missing expected exception (Error).
      at Context.it (test/copy.js:589:20)
```

It _looks_ like an improvement in functionalities though, can you confirm ?

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you for contributing!

**Comment by quilicicf** [comment]
It was a pleasure!

**Comment by HamletDRC** [comment]
@mysticatea can you please make a release? It seems that this fix is not in 1.5.0

**Comment by mallwang** [comment]
Yes, agree. Would be nice if a new release contain this fix.

**Pull request merged**
